x-environment: &environment
  environment:
    DATABASE_URL: "postgresql://postgres:secure_secure_secure_postgres@postgres:5432/gamdom"
 
services:
  postgres:
    &postgres
    restart: always
    image: postgres:15-alpine
    profiles:
      - production
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=secure_secure_secure_postgres
      - PGDATA=/data/postgres
      - POSTGRES_DB=gamdom

  postgres-dev:
    <<: *postgres
    profiles:
      - development
    ports:
      - 45432:5432

volumes:
  postgres:
    driver: local